PACKAGE_NAME="swapz"
PACKAGE_VERSION="0.2.0"
BUILT_MODULE_NAME[0]="dm-swapz"
BUILT_MODULE_LOCATION[0]="kernel"
DEST_MODULE_LOCATION[0]="/updates/dkms"
AUTOINSTALL="yes"
MAKE[0]="make -C kernel KDIR=/lib/modules/${kernelver}/build"
CLEAN="make -C kernel KDIR=/lib/modules/${kernelver}/build clean"
